# Arch Linux specfied recipes
BINDIR=/usr/bin/

$(BINDIR)fzf:
	sudo pacman -S --noconfirm fzf

$(BINDIR)stow:
	sudo pacman -S --noconfirm stow

$(BINDIR)tmux:
	sudo pacman -S --noconfirm tmux
	
$(BINDIR)zsh:
	sudo pacman -S --noconfirm zsh

