# Ubuntu Linux specific recipes
BINDIR=/usr/bin/

$(BINDIR)fzf:
	sudo apt install -y fzf

$(BINDIR)tmux:
	sudo apt install -y tmux

$(BINDIR)stow:
	sudo apt install -y stow

$(BINDIR)zsh:
	sudo apt install -y zsh

