#!/usr/bin/env zsh

# command for LLM interaction in CLI
function zle_llm {
  if (( $+commands[claude] )); then
    builtin print -rn -- $'\e[H\e[2J' >"$TTY";
    (
    set -euo pipefail;

    tmp=$(mktemp -d);
    trap 'rm -rf "$tmp"' EXIT;

    mkdir "$tmp/.claude";

    cd "$tmp";
    claude "$@" || true;
    rm -rf "$tmp"
  )
    zle clear-screen;
  fi
}

