# Python and conda installations
CONDADIR=$(HOME)/.miniconda/
CONDABINDIR=$(CONDADIR)bin/

$(CONDABINDIR)conda: $(BINDIR)curl
	mkdir -p $(CONDADIR)
	curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh | bash -b -u -p $(CONDADIR)

