console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
shell_integration = true
final_space = true

[transient_prompt]
  template = ' {{ .PWD }} $ '
  foreground = 'blue'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'diamond'
    trailing_diamond = ''
    template = '  {{ path .Path .Location }} '
    foreground = 'black'
    background = 'blue'
    type = 'path'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    style = 'diamond'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ end }} '
    foreground = 'black'
    background = 'blue'
    type = 'status'
    background_templates = ['{{ if gt .Code 0 }}red{{ end }}']

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    template = ' {{ if .Venv }}{{ .Venv }}{{ end }} '
    foreground = 'black'
    background = 'green'
    type = 'python'

    [blocks.segments.properties]
      fetch_virtual_env = true

[[tooltips]]
  style = 'diamond'
  leading_diamond = ''
  template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
  foreground = 'black'
  background = 'green'
  type = 'git'
  foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}black{{ end }}', '{{ if gt .Ahead 0 }}black{{ end }}']
  tips = ['git']
  background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}', '{{ if gt .Ahead 0 }}green{{ end }}', '{{ if gt .Behind 0 }}yellow{{ end }}']

  [tooltips.properties]
    branch_max_length = 25
    fetch_status = true
    fetch_upstream_icon = true
