#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    trailing_diamond = ''
    template = '  {{ path .Path .Location }} '
    background = 'p:sky'
    foreground = 'p:black'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:black{{ end }}', '{{ if gt .Ahead 0 }}p:black{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}p:green{{ end }}', '{{ if gt .Behind 0 }}p:yellow{{ end }}']
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    background = 'p:green'
    foreground = 'p:black'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    template = '  '
    background = 'p:yellow'
    foreground = 'p:black'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    # leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ end }} '
    # template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    background = 'p:ice'
    foreground = 'p:black'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    template = ' '
    background = 'transparent'
    foreground = 'p:green'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    template = ' '
    background = 'transparent'
    foreground = 'p:blue'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'python'
    style = 'diamond'
    leading_diamond = ''
    # template = ' {{ .Full }} {{ if .Venv }}{{ .Venv }}{{ end}}'
    template = ' {{ if .Venv }}{{ .Venv }}{{ end }} '

    background = 'p:yellow'
    foreground = 'p:black'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_virtual_env = true

[transient_prompt]
  template = '» '
  background = 'transparent'
  foreground = 'p:green'

[palette]
  black = '#2E3440'

  seafoam = '#8FBCBB'
  sky = '#88C0D0'
  ice = '#81A1C1'
  deep = '#5E81AC'

  snow = '#D8DEE9'
  hail = '#E5E9F0'
  blizzard = '#ECEFF4'

  green = '#A3BE8C'
  orange = '#D08770'
  red = '#BF616a'
  yellow = '#EBCB8B'

