#!/usr/bin/env zsh

# custom update command
function update-all() {
  if command -v paru &>/dev/null; then
    echo 'Updating \033[0;34mArch\033[0m Linux...';
    paru -Syu;
  elif command -v pacman &>/dev/null; then
    echo 'Updating \033[0;34mArch\033[0m Linux...';
    sudo pacman -Syu;
  fi

  if command -v apt &>/dev/null; then
    'Updating \e[0l31mApt\033[0m...';
    sudo apt update;
    sudo apt upgrade;
  fi

  if command -v flatpak &>/dev/null; then
    echo 'Updating \033[1mFlatpak\033[0m...';
    flatpak --user update;
  fi


  if command -v rustup &>/dev/null; then
    echo 'Updating \e[0;31mCargo\033[0m...';
    rustup update;
  fi
  if command -v cargo &>/dev/null; then
    cargo --list | grep install-update;
    cargo install-update --all;
  fi

  if command -v ghcup &>/dev/null; then
    echo 'Updating \033[0;35mghcup\033[0m...';
    ghcup upgrade;
  fi

  if command -v raco &>/dev/null; then
    echo 'Updating \033[0;31mRac\033[0;34mket\033[0m packages...';
    raco pkg update --all;
  fi

  if command -v gem &>/dev/null; then
    echo 'Updating \033[0;31mRubyGems\033[0m packages...';
    gem update;
  fi

  if command -v nvim &>/dev/null; then
    echo 'Updating \033[0;34mNeo\033[1mVim\033[0m packages...';
    nvim --headless "+Lazy! sync" +qa;
    nvim --headless "+TSUpdate" +qa;
    nvim --headless "+MasonUpdate" +qa;
  fi

  if command -v fwupdmgr &>/dev/null; then
    echo 'Updating \033[1mSystem Firmware\033[0m'
    fwupdmgr refresh
    fwupdmgr update
  fi
}
