return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      -- disable treesitter highlight
      highlight = { enable = false },
      indent = { enable = true },
      ensure_installed = {
        "awk",
        "bash",
        "c",
        "cpp",
        "csv",
        "diff",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitcommit",
        "gitattributes",
        "gitignore",
        "go",
        "java",
        "jq",
        "just",
        "json",
        "jsonc",
        "lua",
        "luadoc",
        "luap",
        "make",
        "markdown",
        "markdown_inline",
        "printf",
        "python",
        "query",
        "regex",
        "sql",
        "toml",
        "tsv",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
    },
  },
}
